export const GET_ALL_DOMAINS_REQUEST = "GET_ALL_DOMAINS_REQUEST";
export const GET_ALL_DOMAINS_SUCCESS = "GET_ALL_DOMAINS_SUCCESS";
export const GET_ALL_DOMAINS_FAIL = "GET_ALL_DOMAINS_FAIL";

export const ADD_NEW_DOMAIN_REQUEST = "ADD_NEW_DOMAIN_REQUEST";
export const ADD_NEW_DOMAIN_SUCCESS = "ADD_NEW_DOMAIN_SUCCESS";
export const ADD_NEW_DOMAIN_FAIL = "ADD_NEW_DOMAIN_FAIL";

export const DELETE_DOMAIN_REQUEST = "DELETE_DOMAIN_REQUEST";
export const DELETE_DOMAIN_SUCCESS = "DELETE_DOMAIN_SUCCESS";
export const DELETE_DOMAIN_FAIL = "DELETE_DOMAIN_FAIL";
