export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCCESS = "USER_REGISTER_SUCCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const VERIFY_CODE_REQUEST = "VERIFY_CODE_REQUEST";
export const VERIFY_CODE_SUCCCESS = "VERIFY_CODE_SUCCCESS";
export const VERIFY_CODE_FAIL = "VERIFY_CODE_FAIL";

export const RESEND_CODE_REQUEST = "RESEND_CODE_REQUEST";
export const RESEND_CODE_SUCCCESS = "RESEND_CODE_SUCCCESS";
export const RESEND_CODE_FAIL = "RESEND_CODE_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
